Issue-28 - fixed hardcoding aws region on get_default_region(), allow…
indeni/dragoneye pull request #29
Opened 2021-04-18 12:03 UTC by Tomerva

fix #28

2021-04-18 12:57 UTC, alonashkenazi requested changes

2021-04-18 12:57 UTC, alonashkenazi commented on dragoneye/cloud_scanner/aws/aws_utils.py
> -        default_region = os.environ.get("AWS_REGION", "us-east-1")
why we remove this logic?

2021-04-18 14:35 UTC, Tomerva commented on dragoneye/cloud_scanner/aws/aws_utils.py
> -        default_region = os.environ.get("AWS_REGION", "us-east-1")
Because it makes the region either us-east-1, us-gov-west-1, or cn-north-1 which doesnt really make sense
the region should be decided by the user, and if one is not given, have boto decide the region

2021-04-19 11:01 UTC, Tomerva commented on dragoneye/cloud_scanner/aws/aws_utils.py
> -        default_region = os.environ.get("AWS_REGION", "us-east-1")
i reverted this change, i wrongfuly thought this is the region for creating the session

2021-04-20 06:26 UTC, alonashkenazi approved these changes

2021-04-20 06:26 UTC, merged