Initial readme
indeni/dragoneye pull request #45
Opened 2021-04-21 20:23 UTC by yi2020

2021-04-22 05:16 UTC, alonashkenazi commented
@yi2020 can you use the branch to include the ticket number? I have started a branch for this task you can see this PR: https://github.com/indeni/dragoneye/pull/8/files

2021-04-22 05:23 UTC, alonashkenazi requested changes

2021-04-22 05:23 UTC, alonashkenazi commented on README.md
> +### AWS ###
I think it's worth adding a section that shows that you can pass your own session created by boto3. You don't need to use Dragoneye session factory

2021-04-22 05:23 UTC, alonashkenazi commented on README.md
>  ### For collecting data from AWS
I'm assuming that you still need to work on the CLI documentation right?

2021-04-22 05:23 UTC, alonashkenazi commented on README.md
>  # dragoneye
Things that need to be part of the readme:

- License
- How to triage a bug and how to report a bug
- How to open feature request (https://github.com/hashicorp/terraform/blob/main/BUGPROCESS.md)
- How to contribute (https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md)

2021-04-25 06:42 UTC, Tomerva commented on README.md
>  Create an instance of one of the CollectRequest classes, such as AwsAccessKeyCollectRequest, AwsAssumeRoleCollectRequest, AzureCollectRequest and call the `collect` function. For example:
This text is outdated. The text should now note that each scanner requires the scan settings (AwsCloudScanSettinigs or AzureCloudScanSettings) and the either the session for aws, or the JWT bearer token.

2021-04-25 06:46 UTC, Tomerva commented on README.md
> +session = AwsSessionFactory.get_session(profile_name=None, region='us-east-1')  # Raises exception if authentication is unsuccessful
Perhaps its worth noting that the region could also be taken from environment variable AWS_DEFAULT_REGION

2021-04-26 13:58 UTC, yi2020 commented on README.md
>  # dragoneye
@alonashkenazi please generate the CONTRIBUTING file in this repo and include in the same branch as the readme (CR-2005-create-readme-for-dragoneye) and I'll edit it.

2021-04-26 13:59 UTC, yi2020 commented on README.md
>  # dragoneye
To clarify - you write the process in the CONTRIBUTING file, I just edit it.

2021-04-26 14:02 UTC, yi2020 commented on README.md
> +session = AwsSessionFactory.get_session(profile_name=None, region='us-east-1')  # Raises exception if authentication is unsuccessful
I don't want to make the documentation it too complicated.

2021-04-26 14:03 UTC, closed without merging

2021-04-26 14:04 UTC, yi2020 commented
Replacing this PR with https://github.com/indeni/dragoneye/pull/8