Issue 76 beautify test results
indeni/dragoneye pull request #77
Opened 2021-05-02 14:31 UTC by Tomerva

closes #76

2021-05-02 18:39 UTC, alonashkenazi requested changes

2021-05-02 18:39 UTC, alonashkenazi commented on .github/workflows/ci.yaml
> +    needs: build
this needs pytest block as well

2021-05-02 18:39 UTC, alonashkenazi commented on tests/utils/test_value_validator.py
> +import sys
Why you added an import and didn't change the code?

2021-05-03 06:26 UTC, Tomerva commented on .github/workflows/ci.yaml
> +    needs: build
the pytest block actually runs 1-3 times (per each python version. also 1-3 because if it fails on one version the steps for other versions might be cancelled)

I dont see a way to tell it specifically that it needs atleast 1 step from the above matrix.

As it is described right now, the publish test results job will always run, which means it will needlessly run only when there is a pylint error for all python versions

2021-05-03 07:27 UTC, alonashkenazi approved these changes

2021-05-03 07:27 UTC, merged